spring.application.name=microprojeto-04

spring.datasource.url=jdbc:postgresql://localhost:5432/petsdb
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true